FROM oven/bun:1.0

RUN apt-get update &&\
    apt-get install -y inotify-tools &&\
    # clean up apt
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
ENV NODE_ENV=development

COPY package.json .
COPY bun.lockdb .
RUN bun install

COPY . .

ENV DEVSERVER_URL=http://0.0.0.0:3036
CMD bun dev